name: Build Image and Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Checkout LFS objects
        run: git lfs pull

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          cd tawsyla_backend
          docker build -t tawsyla-backend:${{ github.sha }} .
          docker tag tawsyla-backend:${{ github.sha }} tawsyla-backend:latest

      - name: Save Docker Image
        run: |
          docker save tawsyla-backend:latest | gzip > tawsyla-backend.tar.gz

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

      - name: Add droplet to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts

      - name: Transfer Docker Image to Droplet
        env:
          DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
          DROPLET_USERNAME: ${{ secrets.DROPLET_USERNAME }}
        run: |
          # Create deployment directory on droplet
          ssh $DROPLET_USERNAME@$DROPLET_HOST "mkdir -p /opt/tawsyla"
          
          # Sync ALL project files to droplet
          rsync -avz --delete \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude 'dist' \
            --exclude 'build' \
            --exclude '.next' \
            --exclude 'coverage' \
            --exclude 'tawsyla-backend.tar.gz' \
            ./ $DROPLET_USERNAME@$DROPLET_HOST:/opt/tawsyla/
          
          # Make deployment scripts executable
          ssh $DROPLET_USERNAME@$DROPLET_HOST "chmod +x /opt/tawsyla/.github/scripts/*.sh"
          
          # Transfer the Docker image
          scp tawsyla-backend.tar.gz $DROPLET_USERNAME@$DROPLET_HOST:/opt/tawsyla/

      - name: Load and Run Docker Image
        env:
          DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
          DROPLET_USERNAME: ${{ secrets.DROPLET_USERNAME }}
        run: |
          ssh -T $DROPLET_USERNAME@$DROPLET_HOST "/opt/tawsyla/.github/scripts/deploy-image.sh"

      - name: Cleanup
        if: always()
        run: |
          rm -f tawsyla-backend.tar.gz
