name: Build and Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

      - name: Add droplet to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean Droplet
        env:
          DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
          DROPLET_USERNAME: ${{ secrets.DROPLET_USERNAME }}
        run: |
          # Create deployment directory on droplet if it doesn't exist
          ssh $DROPLET_USERNAME@$DROPLET_HOST "mkdir -p /opt/tawsyla"
          
          # Copy files to droplet (excluding node_modules and other large files)
          rsync -avz --delete \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude 'dist' \
            --exclude 'build' \
            --exclude '.next' \
            --exclude 'coverage' \
            ./ $DROPLET_USERNAME@$DROPLET_HOST:/opt/tawsyla/
          
          # Make deployment scripts executable
          ssh $DROPLET_USERNAME@$DROPLET_HOST "chmod +x /opt/tawsyla/.github/scripts/*.sh"

      - name: Build and Start Docker Containers
        env:
          DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
          DROPLET_USERNAME: ${{ secrets.DROPLET_USERNAME }}
        run: |
          ssh -T $DROPLET_USERNAME@$DROPLET_HOST "/opt/tawsyla/.github/scripts/deploy.sh"

      - name: Health Check
        env:
          DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
          DROPLET_USERNAME: ${{ secrets.DROPLET_USERNAME }}
        run: |
          ssh -T $DROPLET_USERNAME@$DROPLET_HOST "/opt/tawsyla/.github/scripts/health-check.sh"
